### ISSUE TITLE
Cleanup pg2kafka.outbound_event_queue table

### ISSUE THREAD

**Issue by sermojohn** [codebgp/pg2kafka#6]
**Is your feature request related to a problem? Please describe.**
When monitoring `pg2kafka.outbound_event_queue` table we can see its size bloating during normal operation.

**Describe the solution you'd like**
pg2kafka.outbound_event_queue records are updated when processed and never used again by pg2kafka. We should apply a maintenance policy such as delete records after X period to avoid filling the disk. This solution should also improve the performance of the table.

**Comment by vkotronis** [comment]
TODO: instead of marking as processed, delete the event from the outbound queue table altogether asynchronously

https://github.com/codebgp/pg2kafka/blob/main/eventqueue/event_queue.go#L24

**Comment by vkotronis** [comment]
optionally: in https://github.com/codebgp/pg2kafka/blob/main/main.go#L146 report the size of the outbound queue table (every 90 seconds, when we ping)

**Comment by vkotronis** [comment]
Completed
