### ISSUE TITLE
Investigate problematic behavior of pg2kafka

### ISSUE THREAD

**Issue by vkotronis** [codebgp/pg2kafka#8]
```
Server started
2022-09-02T16:16:28.563Z	INFO	pg2kafka/main.go:73	Not performing database migrations due to missing `PERFORM_MIGRATIONS`.
2022-09-02T16:16:28.599Z	INFO	pg2kafka/main.go:102	pg2kafka[commit:c86d745] started
2022-09-02T16:17:04.356Z	INFO	pg2kafka/main.go:108	pg2kafka[commit:c86d745] is now listening to notifications
2022-09-02T16:17:04.531Z	ERROR	pg2kafka/main.go:82	Error handling postgres notify	{"error": "pq: terminating connection due to administrator command"}
main.main.func2
	github.com/codebgp/pg2kafka/main.go:82
github.com/lib/pq.(*Listener).emitEvent
	github.com/lib/pq@v1.10.2/notify.go:797
github.com/lib/pq.(*Listener).listenerConnLoop
	github.com/lib/pq@v1.10.2/notify.go:849
github.com/lib/pq.(*Listener).listenerMain
	github.com/lib/pq@v1.10.2/notify.go:856
```

Sometimes this may get "stuck" as shown above, not consuming the PG queue messages thus leading to the entire DB lagging behind. Needs debugging.

**Comment by vkotronis** [comment]
in case the last active log is not sth like
```
main-db2broker_1           | 2022-09-05T11:41:13.692Z	INFO	pg2kafka/main.go:102	pg2kafka[commit:c86d745] started
```
we should consider the broker unhealthy and recover

**Comment by akazantzidis** [comment]
> 2022-09-02T16:17:04.531Z	ERROR	pg2kafka/main.go:82	Error handling postgres notify	{"error": "pq: terminating connection due to administrator command"}

Can we catch the:
`2022-09-02T16:17:04.531Z	ERROR	pg2kafka/main.go:82	Error handling postgres notify	{"error": "pq: terminating connection due to administrator command"}
`  ?  For the healthcheck and recovery

**Comment by vkotronis** [comment]
Anything related to the 'notify' errors should be caught and lead to service restart until it is stable

**Comment by vkotronis** [comment]
correct (healthy) log sequence:
```
2022-08-30T15:31:53.823Z	INFO	pg2kafka/main.go:102	pg2kafka[commit:c86d745] started
2022-08-30T15:31:54.776Z	INFO	pg2kafka/main.go:108	pg2kafka[commit:c86d745] is now listening to notifications
```

**Comment by vkotronis** [comment]
Possibly related to https://github.com/codebgp/pg2kafka/issues/6

**Comment by sermojohn** [comment]
When stopping the database on which a listen/notify connection is established by pg2kafka, the following error logs are shown:

```
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157937055Z 2022-09-07T07:44:36.157Z	ERROR	pg2kafka/main.go:82	Error handling postgres notify	{"error": "pq: terminating connection due to administrator command"}
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157964296Z main.main.func2
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157969786Z 	github.com/codebgp/pg2kafka/main.go:82
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157974475Z github.com/lib/pq.(*Listener).emitEvent
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157978781Z 	github.com/lib/pq@v1.10.2/notify.go:797
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157983224Z github.com/lib/pq.(*Listener).listenerConnLoop
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157987531Z 	github.com/lib/pq@v1.10.2/notify.go:849
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157991872Z github.com/lib/pq.(*Listener).listenerMain
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157997701Z 	github.com/lib/pq@v1.10.2/notify.go:856
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.175286010Z 2022-09-07T07:44:36.161Z	ERROR	pg2kafka/main.go:82	Error handling postgres notify	{"error": "pq: the database system is shutting down"}
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185517598Z main.main.func2
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185530461Z 	github.com/codebgp/pg2kafka/main.go:82
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185535356Z github.com/lib/pq.(*Listener).emitEvent
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185539545Z 	github.com/lib/pq@v1.10.2/notify.go:797
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185543837Z github.com/lib/pq.(*Listener).listenerConnLoop
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185549415Z 	github.com/lib/pq@v1.10.2/notify.go:817
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185553588Z github.com/lib/pq.(*Listener).listenerMain
bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185557670Z 	github.com/lib/pq@v1.10.2/notify.go:856
bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186515182Z 2022-09-07T07:44:51.181Z	ERROR	pg2kafka/main.go:82	Error handling postgres notify	{"error": "dial tcp: lookup main-database: Try again"}
bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186543939Z main.main.func2
bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186549467Z 	github.com/codebgp/pg2kafka/main.go:82
bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186554206Z github.com/lib/pq.(*Listener).emitEvent
bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186559830Z 	github.com/lib/pq@v1.10.2/notify.go:797
bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186564468Z github.com/lib/pq.(*Listener).listenerConnLoop
bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186568817Z 	github.com/lib/pq@v1.10.2/notify.go:817
bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186573174Z github.com/lib/pq.(*Listener).listenerMain
bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186578259Z 	github.com/lib/pq@v1.10.2/notify.go:856
bgp-data-main-db2broker-1  | 2022-09-07T07:45:19.129144048Z 2022-09-07T07:45:19.128Z	FATAL	pg2kafka/main.go:148	Error pinging listener	{"error": "no connection"}
bgp-data-main-db2broker-1  | 2022-09-07T07:45:19.129172562Z main.waitForNotification.func1
bgp-data-main-db2broker-1  | 2022-09-07T07:45:19.129176103Z 	github.com/codebgp/pg2kafka/main.go:148
```

pg2kafka recovers after restart and when database is up and accepting connections.

**Comment by vkotronis** [comment]
> When stopping the database on which a listen/notify connection is established by pg2kafka, the following error logs are shown:
> 
> ```
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157937055Z 2022-09-07T07:44:36.157Z	ERROR	pg2kafka/main.go:82	Error handling postgres notify	{"error": "pq: terminating connection due to administrator command"}
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157964296Z main.main.func2
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157969786Z 	github.com/codebgp/pg2kafka/main.go:82
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157974475Z github.com/lib/pq.(*Listener).emitEvent
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157978781Z 	github.com/lib/pq@v1.10.2/notify.go:797
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157983224Z github.com/lib/pq.(*Listener).listenerConnLoop
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157987531Z 	github.com/lib/pq@v1.10.2/notify.go:849
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157991872Z github.com/lib/pq.(*Listener).listenerMain
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.157997701Z 	github.com/lib/pq@v1.10.2/notify.go:856
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.175286010Z 2022-09-07T07:44:36.161Z	ERROR	pg2kafka/main.go:82	Error handling postgres notify	{"error": "pq: the database system is shutting down"}
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185517598Z main.main.func2
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185530461Z 	github.com/codebgp/pg2kafka/main.go:82
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185535356Z github.com/lib/pq.(*Listener).emitEvent
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185539545Z 	github.com/lib/pq@v1.10.2/notify.go:797
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185543837Z github.com/lib/pq.(*Listener).listenerConnLoop
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185549415Z 	github.com/lib/pq@v1.10.2/notify.go:817
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185553588Z github.com/lib/pq.(*Listener).listenerMain
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:36.185557670Z 	github.com/lib/pq@v1.10.2/notify.go:856
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186515182Z 2022-09-07T07:44:51.181Z	ERROR	pg2kafka/main.go:82	Error handling postgres notify	{"error": "dial tcp: lookup main-database: Try again"}
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186543939Z main.main.func2
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186549467Z 	github.com/codebgp/pg2kafka/main.go:82
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186554206Z github.com/lib/pq.(*Listener).emitEvent
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186559830Z 	github.com/lib/pq@v1.10.2/notify.go:797
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186564468Z github.com/lib/pq.(*Listener).listenerConnLoop
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186568817Z 	github.com/lib/pq@v1.10.2/notify.go:817
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186573174Z github.com/lib/pq.(*Listener).listenerMain
> bgp-data-main-db2broker-1  | 2022-09-07T07:44:51.186578259Z 	github.com/lib/pq@v1.10.2/notify.go:856
> bgp-data-main-db2broker-1  | 2022-09-07T07:45:19.129144048Z 2022-09-07T07:45:19.128Z	FATAL	pg2kafka/main.go:148	Error pinging listener	{"error": "no connection"}
> bgp-data-main-db2broker-1  | 2022-09-07T07:45:19.129172562Z main.waitForNotification.func1
> bgp-data-main-db2broker-1  | 2022-09-07T07:45:19.129176103Z 	github.com/codebgp/pg2kafka/main.go:148
> ```

OK so it is sth normal when the DB stops. Does it recover when it restarts? Or does the  broker fail, stop and  restart?

**Comment by vkotronis** [comment]
@sermojohn since you already tested this locally, does `pg2kfka` recover when the database restarts? Or does it fail, stop and restart? Either case is OK as long as it recovers and it does not remain "stuck".

**Comment by sermojohn** [comment]
> @sermojohn since you already tested this locally, does `pg2kfka` recover when the database restarts? Or does it fail, stop and restart? Either case is OK as long as it recovers and it does not remain "stuck".

Yes, pg2kafka recovers.

I am currently making some modifications so the process does not restart on disconnections, because the pq library used for connecting to postgres actually recovers the connection. This will let pg2kafka have more consistent behaviour and let us debug it in a following round, if we still have issues.

**Comment by vkotronis** [comment]
> > @sermojohn since you already tested this locally, does `pg2kfka` recover when the database restarts? Or does it fail, stop and restart? Either case is OK as long as it recovers and it does not remain "stuck".
> 
> Yes, pg2kafka recovers.
> 
> I am currently making some modifications so the process does not restart on disconnections, because the pq library used for connecting to postgres actually recovers the connection. This will let pg2kafka have more consistent behaviour and let us debug it in a following round, if we still have issues.

Perfect, very nice catch @sermojohn

**Comment by sermojohn** [comment]
First of all, pg2kafka is a simplistic implementation of CDC patter. It uses database triggers to track changes and reads changes from the same database to push events to Kafka. This approach pushes big load to postgres, which it does not affect broker. So, if we want to remove load from postgres to increase performance, we should definitely consider moving to another implementation of CDC.

pg2kafka also proved to be a draft implementation of CDC pattern, for the following reasons:
1. Crashes on any error and triggers a restart.
2. No throttling to the listen/notify events received by postgres, so every notification results to hitting the database, even when events are available in the queue. For example, on high load when multiple records are modified and multiple notifications are sent for every change, if pg2kafka cannot keepup with the notifications, one notification will actually cause the processing of 1-1000 events, so the following notifications could trigger pg2kafka to hit the database without event to process.
3. Kafka producer blocks forever if Kafka is unavailable.

For the above reasons, we should consider the following options:
1. Switch implementation of CDD
2. Refactor and fix pg2kafka

**Comment by vkotronis** [comment]
> First of all, pg2kafka is a simplistic implementation of CDC patter. It uses database triggers to track changes and reads changes from the same database to push events to Kafka. This approach pushes big load to postgres, which it does not affect broker. So, if we want to remove load from postgres to increase performance, we should definitely consider moving to another implementation of CDC.
> 
> pg2kafka also proved to be a draft implementation of CDC pattern, for the following reasons:
> 
> 1. Crashes on any error and triggers a restart.
> 2. No throttling to the listen/notify events received by postgres, so every notification results to hitting the database, even when events are available in the queue. For example, on high load when multiple records are modified and multiple notifications are sent for every change, if pg2kafka cannot keepup with the notifications, one notification will actually cause the processing of 1-1000 events, so the following notifications could trigger pg2kafka to hit the database without event to process.
> 3. Kafka producer blocks forever if Kafka is unavailable.
> 
> For the above reasons, we should consider the following options:
> 
> 1. Switch implementation of CDD
> 2. Refactor and fix pg2kafka

Thanks for the comprehensive analysis Gianni.
I would  go with option 2 (in stages) since also in our design discussion in May we could not find a simpler and easier to use  (and tune) framework. Regarding point 2 (`No throttling to the listen/notify events received by postgres`) could you introduce a small throttler component in-pg2kafka like you have done in other mservices? This will result in hitting the DB only when needed.

**Comment by sermojohn** [comment]
The PR improved database statistics, so this issue is closed.
